spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    client-service: /client/**
    contrat-service: /contrat/**
    vente-service: /vente/**
#security:
#  oauth2:
#    resource:
#      userInfoUri: http://192.168.99.100:8181/uaa/user
#  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    client-service: /client/**
    contrat-service: /contrat/**
    vente-service: /vente/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/