spring:
  profiles: docker
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

management.security.enabled: false
